### ISSUE TITLE
Automate Relase Process

### ISSUE THREAD

**Issue by bauerj** [bauerj/paperless_app#66]
Currently, the release process is a manual task. Ideally, release and testing would be automated so that the effort could be directed to improving the app. This will be especially important when we have an iOS version, since that doubles the workload.

I think the following steps need to be done:

- [ ] Set up a Paperless test server with some documents for use while testing the app
- [ ] Make Github Actions compile APKs
  - [ ] Add a new action
  - [ ] Securely store signing key
  - [ ] Store the artifacts
- [ ] Automatically generate changelog
- [ ] Add APKs to a new Github Release
- [ ] Upload APKs to Google Play
- [ ] Integration Testing (basically a robot using the app in an emulator)
- [ ] Automate taking screenshots of the app while testing (for Github/F-Droid)

**Comment by qcasey** [comment]
Anyone looking to help with this can freely use our demo server:

https://paperless-demo.quinncasey.com/
**Username:** paperless
**Password:** paperless

The demo resets itself daily.
